media_player:
  - platform: xiaofang_mediaplayer
    ip_address: "192.168.1.42"
    port: 11032
    message: "Test message"
    volume: 0.2
#    cache_dir: /tmp/tts    # Optional - make sure it matches the same setting in TTS config
